# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: .+.diff$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.7'
    hooks:
    -   id: autopep8
        args: [--in-place, --max-line-length=120]
-   repo: https://github.com/PyCQA/pylint
    rev: 'v2.11.1'
    hooks:
    -   id: pylint
-   repo: local
    hooks:
        - id: license-tools
          name: Check license headers
          entry: ./lictool
          language: python
          types: [text]
          require_serial: true
          additional_dependencies: ['jinja2']
